# Generated by Django 4.2 on 2023-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="timestamp",
            field=models.DateTimeField(default="2023-05-27 00:00:00"),
        ),
    ]
