# Generated by Django 4.2 on 2023-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_comments_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="timestamp",
            field=models.DateTimeField(default="2023-05-27 00:00:00"),
        ),
    ]
