# Generated by Django 4.2 on 2023-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_history_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="timestamp",
            field=models.DateField(default="2023-05-24"),
        ),
    ]
