# Generated by Django 4.2 on 2023-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bookmark_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="timestamp",
            field=models.DateTimeField(default="2023-06-06 00:00:00"),
        ),
    ]
