# Generated by Django 4.2.1 on 2023-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comments_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='AuthorImg/default.jpg', upload_to='AuthorImg', verbose_name='作者头像')),
                ('profile', models.TextField(default='这个人很懒，什么都没有留下~')),
            ],
        ),
    ]
